version: '3.1'
services:
  melon:
    image: melon
    build: .
    container_name: melon
    expose:
      - 5000
    env_file:
      - .env
    volumes:
      - ./static:/app/static
      - ./data:/app/data
    networks:
      - nginx_backend

networks:
  nginx_backend:
    external: true
